In [2]:
!pip3 install numpy

# We are going to learn numpy

##### This is headline

In [5]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3], [4, 2, 5]])

In [14]:
type(arr)

numpy.ndarray

In [16]:
arr.ndim

2

In [22]:
arr.shape

(2, 3)

In [24]:
arr.size

6

In [26]:
arr.dtype

dtype('int32')

In [28]:
np.array([1, 23, 3])

array([ 1, 23,  3])

In [32]:
np.array((1,2 ,3,4))

array([1, 2, 3, 4])

In [38]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.arange(3, 15, 1)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
np.linspace(3, 23,5)

array([ 3.,  8., 13., 18., 23.])

In [60]:
np.random.random((2, 3))

array([[0.55969643, 0.3392437 , 0.38895287],
       [0.34441065, 0.99167224, 0.0019137 ]])

In [66]:
arr = np.array([[1, 2, 3, 7], [5, 2, 4, 99], [6, 7, 7,8]])
arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 7,  5,  2]],

       [[ 4, 99,  6],
        [ 7,  7,  8]]])

In [68]:
arr.flatten()

array([ 1,  2,  3,  7,  5,  2,  4, 99,  6,  7,  7,  8])

In [9]:
arr = np.array([[-1, 2, 0, 4], [4 ,-0.5, 6, 0], [2.6, 0, 7, 8],[2.6, 0, 7, 8], [3, -7, 4, 2.0]])

In [92]:
arr[1:, :-1:2]

array([[4. , 6. ],
       [2.6, 7. ],
       [2.6, 7. ],
       [3. , 4. ]])

In [96]:
cond = arr > 0
arr[cond]

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 2.6, 7. , 8. , 3. , 4. , 2. ])

In [11]:
arr+1

array([[ 0. ,  3. ,  1. ,  5. ],
       [ 5. ,  0.5,  7. ,  1. ],
       [ 3.6,  1. ,  8. ,  9. ],
       [ 3.6,  1. ,  8. ,  9. ],
       [ 4. , -6. ,  5. ,  3. ]])

In [13]:
arr.T

array([[-1. ,  4. ,  2.6,  2.6,  3. ],
       [ 2. , -0.5,  0. ,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  8. ,  2. ]])

In [17]:
arr.sum(axis=1)

array([ 5. ,  9.5, 17.6, 17.6,  2. ])

In [33]:
a = [[1, 2], [3, 4]]
b= [[5,6],[7,8]]

In [23]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
np.concatenate((a, b), 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])